const database = require("../db");

// Each entry is: English word | Chinese meaning.  These are deliberately words
// only: examples are stored as an empty string.
const wordBanks = {
  1: `
abandon|放弃
abolish|废除
abrupt|突然的
absorb|吸收
abstract|抽象的
accelerate|加速
accommodate|容纳、适应
accomplish|完成
accumulate|积累
accurate|准确的
achieve|实现
acquire|获得
activate|激活
acute|严重的、敏锐的
adjacent|相邻的
advocate|倡导
aggregate|总计、集合
align|使一致
alternative|替代方案
amend|修改
annual|每年的
apparent|显然的
append|附加
appreciate|理解、欣赏
assemble|组装、集合
attain|达到
attribute|归因于、属性
authorise|授权
automate|自动化
benefit|益处
brief|简短的
cease|停止
challenge|挑战
channel|渠道
cite|引用
civil|公民的、文明的
coincide|同时发生、一致
commence|开始
commodity|商品
communicate|沟通
compatible|兼容的
compile|编写、汇编
complement|补充
component|组成部分
compound|复合物、加重
comprise|包含、由…组成
conceive|构想、怀孕
concentrate|集中
concurrent|同时发生的
conduct|进行、行为
confirm|确认
conflict|冲突
conform|遵从、一致
consent|同意
consequent|随之发生的
consider|考虑
constitute|构成
contemporary|当代的
contract|合同、收缩
convert|转换
convince|说服
coordinate|协调
core|核心
corporate|公司的
correspond|相对应
couple|一对、结合
create|创造
cycle|周期
data|数据
debate|辩论
decade|十年
decline|下降、拒绝
deduce|推断
define|定义
deny|否认
detect|发现
deviate|偏离
device|设备
dimension|维度
domestic|国内的、家庭的
dominate|主导
draft|草稿
duration|持续时间
dynamic|动态的
economy|经济
edit|编辑
element|元素
eliminate|消除
emerge|出现
enable|使能够
enforce|执行、强制
ensure|确保
entity|实体
equip|装备
erode|侵蚀、削弱
estate|地产、财产
estimate|估计
ethnic|民族的
exceed|超过
exclude|排除
exhibit|展示
expand|扩大
expert|专家
explicitly|明确地
extract|提取
federal|联邦的
feature|特点
final|最终的
finance|金融、资金
finite|有限的
focus|焦点、专注
format|格式
foundation|基础
function|功能、作用
fund|资金
fundamental|基本的
generate|产生
goal|目标
grant|授予、补助金
guarantee|保证
guideline|指导原则
highlight|突出显示
identify|识别
illustrate|说明
impact|影响
incorporate|纳入
index|指数、索引
indicate|表明
individual|个人、个体
induce|引起
inequality|不平等
initial|最初的
input|输入、投入
insert|插入
inspect|检查
instance|例子
instruct|指导
intelligent|聪明的
intense|强烈的
invest|投资
investigate|调查
issue|问题、发布
item|项目
job|工作
journal|期刊
justify|证明合理
label|标签
labour|劳动
layer|层次
lecture|讲座
legal|法律的
legislate|立法
licence|许可证
link|联系
locate|定位
logic|逻辑
major|主要的
manual|手册、手动的
margin|边缘、利润
mature|成熟的
maximise|最大化
mechanism|机制
media|媒体
medical|医学的
mental|精神的
method|方法
migrate|迁移
minimal|最小的
minimise|最小化
minor|次要的
modify|修改
monitor|监测
network|网络
neutral|中立的
nevertheless|然而
normal|正常的
obtain|获得
obvious|明显的
occupy|占据
occur|发生
overall|总体的
participate|参加
partner|伙伴
percent|百分比
period|时期
persist|坚持、持续
phase|阶段
phenomenon|现象
policy|政策
portion|部分
pose|造成、提出
positive|积极的
potential|潜力、潜在的
precede|在…之前
precise|精确的
predict|预测
previous|以前的
primary|主要的
principle|原则
proceed|继续进行
process|过程
professional|专业的
project|项目
promote|促进
proportion|比例
publish|出版
purchase|购买
range|范围
react|反应
recover|恢复
region|地区
register|注册
reject|拒绝
relate|关联
rely|依靠
remove|移除
require|需要
research|研究
respond|回应
restrict|限制
retain|保留
reveal|揭示
review|审查
role|角色
route|路线
scenario|情景
schedule|日程
sector|领域
secure|安全的、获得
seek|寻求
select|选择
series|系列
shift|转变
significant|重要的
similar|相似的
site|地点
source|来源
specific|具体的
stable|稳定的
statistic|统计数据
status|状态
strategy|策略
stress|压力、强调
structure|结构
submit|提交
subsequent|随后的
sum|总数
summary|总结
survey|调查
survive|生存
symbol|符号
target|目标
task|任务
technical|技术的
technique|技巧
technology|技术
text|文本
theme|主题
theory|理论
therefore|因此
topic|话题
tradition|传统
transfer|转移
transform|改变
trend|趋势
trial|试验
ultimate|最终的
undergo|经历
undertake|承担
uniform|统一的
utilise|利用
valid|有效的
vary|变化
vehicle|车辆、媒介
version|版本
via|通过
visual|视觉的
volume|数量、体积
voluntary|自愿的
wealth|财富
whereas|然而、鉴于
withdraw|撤回
yield|产生、产量`,
  2: `
aberration|异常、偏差
abide|遵守、忍受
abstain|弃权、克制
abundant|充裕的
accede|同意、就任
accentuate|强调
acclaim|称赞
accrue|累积增长
adverse|不利的
affinity|亲和力、密切关系
albeit|尽管
allege|声称
allocate|分配
ambivalent|矛盾的
analogous|类似的
annex|附加、吞并
anterior|前面的
antithetical|对立的
appease|安抚
arbitrary|任意的
articulate|清晰表达
ascertain|查明
assert|断言
assimilate|吸收、同化
attenuate|减弱
auditable|可审计的
augment|增加、扩大
authentic|真实的
baseline|基准线
benchmark|基准
bias|偏见
burden|负担
capability|能力
catalyst|催化剂
coerce|强迫
cohesion|凝聚力
collateral|附属的、抵押物
commensurate|相称的
compliance|遵从
concede|承认、让步
concurrent|并发的
confound|混淆
consecutive|连续的
constrain|约束
contend|争辩
contiguous|相邻的
contravene|违反
convene|召集
corroborate|证实
credible|可信的
criterion|准则
crucial|关键的
culminate|达到顶点
curtail|削减
degrade|降级、恶化
delineate|描绘界限
denote|表示
deplete|耗尽
deploy|部署
derive|推导、获得
detectable|可察觉的
detract|减损
deviance|偏差行为
discrete|分离的
displace|取代、迁移
disseminate|传播
distinct|不同的
diverge|分歧、偏离
elaborate|详细说明
eligible|有资格的
emphasis|重点
encompass|包含
endemic|地方性流行的
envisage|设想
equitable|公平的
equivalent|等价的
eradicable|可根除的
escalate|升级
ethical|合乎道德的
exacerbate|加剧
exempt|豁免的
exhaustive|详尽的
exogenous|外生的
expedite|加快
expenditure|支出
extractive|开采性的
facilitate|促进
factual|事实的
feasible|可行的
fidelity|忠实度
fluctuate|波动
formulate|制定
forthcoming|即将到来的
foster|促进、培养
friction|摩擦、冲突
fundamental|根本的
generic|通用的
governance|治理
gradual|渐进的
granular|细粒度的
heuristic|启发式方法
homogeneous|同质的
hostile|敌对的
identical|相同的
ideological|意识形态的
illuminate|阐明
immutable|不可改变的
imperative|必要的、命令
incentivise|激励
incidence|发生率
incompatible|不兼容的
incremental|逐步增加的
indigenous|本土的
inevitable|不可避免的
inhibit|抑制
integral|不可或缺的
intervene|干预
intrinsic|内在的
inverse|相反的
invoke|援引、调用
iterate|重复、迭代
jurisdiction|管辖权
latent|潜在的
leverage|利用、杠杆
liable|有责任的
likelihood|可能性
linear|线性的
longitudinal|纵向的
manifest|显现的
mediate|调解、居中
methodical|有条理的
mitigate|缓解
multilateral|多边的
normative|规范性的
notwithstanding|尽管
objective|客观的、目标
offset|抵消
operational|可操作的
optimal|最佳的
ordinate|排序、坐标
outcome|结果
overlap|重叠
paradigm|范式
perceive|察觉、理解
perpetuate|使持续
pertinent|相关的
plausible|貌似合理的
precedent|先例
predominant|占主导的
preliminary|初步的
presume|假定
prevalent|普遍的
principal|主要的、负责人
proactive|主动的
procure|取得、采购
prohibit|禁止
proliferate|激增
prospective|预期的
protocol|协议、规程
quantify|量化
radical|根本的、激进的
random|随机的
ratio|比率
reconcile|调和
redundant|多余的
regime|制度、体制
reluctant|不情愿的
remedy|补救办法
replicate|复制、重复验证
respective|各自的
retrospective|回顾性的
robust|稳健的
scenario|情景
scheme|方案
scope|范围
selective|选择性的
simulate|模拟
solely|仅仅
specified|指定的
sporadic|零星的
static|静态的
stimulate|刺激、促进
straightforward|直接明了的
subordinate|下级的、从属的
subsidy|补贴
substantive|实质性的
supplement|补充
surplus|盈余
susceptible|易受影响的
synthesise|综合
tangible|有形的
tentative|暂定的
terminate|终止
traceable|可追溯的
ubiquitous|无处不在的
unilateral|单方面的
underlying|潜在的、根本的
unprecedented|前所未有的
viable|可行的
volatile|易变的
whereby|凭借、通过
withstand|承受、抵挡
abrogate|废除
abusive|滥用的、辱骂的
accelerated|加速的
acquisitive|贪求的
adaptive|适应性的
additive|附加的
adequacy|充分性
administrative|行政的
admissible|可接受的
adversarial|对抗性的
aesthetic|审美的
affective|情感的
aggregate|总量、聚集
altruistic|利他的
ambiguous|模棱两可的
analytical|分析性的
anecdotal|轶事性的
anonymity|匿名性
antecedent|先前的、先行条件
applicable|适用的
arbitrate|仲裁
artificial|人工的
aspirational|理想性的
assessable|可评估的
asymmetric|不对称的
attitudinal|态度上的
attributable|可归因的
audience|受众
authoritative|权威性的
beneficiary|受益人
bilateral|双边的
calibrate|校准
coherent|连贯的
collective|集体的
comparable|可比较的
compelling|令人信服的
competence|胜任能力
complementary|互补的
complex|复杂的
concession|让步
conformance|符合、一致`,
  3: `
abstraction|抽象概念
accretion|逐渐增长
adaptability|适应能力
adjudicate|裁决
aggregate|聚合
allegiance|忠诚
amplify|放大
anticipatory|预期性的
archetype|原型
articulation|表达、衔接
asymmetry|不对称
autonomy|自主性
causality|因果关系
centralisation|集中化
coercion|强制
cognition|认知
coherence|连贯性
commodification|商品化
complementarity|互补性
conceptualise|概念化
configuration|配置、构型
congruence|一致性
connotation|内涵
consolidation|巩固、整合
contingency|偶然性、应急情况
continuity|连续性
convergence|趋同
correlation|相关性
decentralisation|分散化
deduction|演绎
deliberation|审议、慎思
demarcation|界定
denomination|名称、面额
derivation|推导
descriptive|描述性的
determinant|决定因素
dichotomy|二分法
diffusion|扩散
discourse|话语
disparity|差距
disposition|倾向、性情
distinction|区别
doctrine|学说
eclectic|兼收并蓄的
elasticity|弹性
elucidate|阐明
embodiment|体现
emancipation|解放
empirical|实证的
epistemic|认识论的
equilibrium|均衡
essentialism|本质主义
explanatory|解释性的
extrapolate|推断、外推
falsifiable|可证伪的
fragmentation|碎片化
genealogy|谱系学
generalisation|概括
hegemony|霸权
heterogeneity|异质性
homogeneity|同质性
idealisation|理想化
impartiality|公正性
inference|推论
institutionalise|制度化
instrumental|工具性的
integration|整合
interdependence|相互依存
interpretive|解释性的
intersection|交叉点
juxtaposition|并置
legitimation|合法化
linearity|线性特征
manifestation|表现
mediation|调解、中介
methodology|方法论
modality|形式、情态
modernity|现代性
multidimensional|多维的
mutuality|相互性
ontology|本体论
operationalise|操作化
paradigmatic|范式性的
permeability|渗透性
pluralism|多元主义
polarisation|两极化
positionality|立场性
predisposition|倾向性
prerequisite|先决条件
presupposition|预设
probabilistic|概率性的
proposition|命题
qualitative|定性的
quantitative|定量的
reciprocity|互惠性
reconfiguration|重新配置
reductionism|还原主义
reflexivity|反思性
relational|关系性的
representation|表征
reproduction|再生产
salience|显著性
segmentation|分割
semantic|语义的
simultaneity|同时性
sovereignty|主权
specification|具体说明
stratification|分层
subjectivity|主观性
substitution|替代
symmetry|对称性
synchronise|同步
synthesis|综合
taxonomy|分类体系
teleology|目的论
terminology|术语
theorise|理论化
transformation|转变
transitional|过渡性的
triangulation|三角互证
typology|类型学
uniformity|一致性
validity|有效性
variability|可变性
volatility|波动性
abductive|溯因的
accommodative|调适性的
anomalous|异常的
asymmetrical|不对称的
causal|因果的
contextual|语境相关的
discursive|话语的
divergent|分歧的
embedded|嵌入的
equivocal|模棱两可的
inferential|推理的
interdisciplinary|跨学科的
methodological|方法论的
polarised|两极化的
reciprocal|互惠的
salient|显著的
sovereign|自主的、主权的
synthetic|综合的
volatile|不稳定的
accounting|核算
acquiescence|默许
affiliation|隶属关系
agency|能动性、机构
ambiguity|歧义
appraisal|评价
assumption|假设
attribution|归因
boundary|边界
calibration|校准
categorisation|分类
circulation|流通
clarification|澄清
coexistence|共存
comparability|可比性
compensation|补偿
complexity|复杂性
composition|构成
comprehension|理解
computation|计算
conception|概念
conclusion|结论
conformity|一致、遵从
constraint|限制
contradiction|矛盾
credibility|可信性
deviation|偏差
differentiation|区分
dissemination|传播
distortion|扭曲
diversity|多样性
dominance|支配地位
emergence|出现
equivalence|等值性
evaluation|评估
exclusion|排除
exploitation|利用、剥削
feasibility|可行性
flexibility|灵活性
formulation|制定
framework|框架
hierarchy|层级
hypothesis|假设
ideology|意识形态
implication|含义、影响
inclusion|纳入
indeterminacy|不确定性
individualisation|个体化
inequality|不平等
infrastructure|基础设施
inquiry|探究
instability|不稳定性
legitimacy|正当性
limitation|局限
materiality|物质性
momentum|动力、势头
necessity|必要性
neutrality|中立性
normativity|规范性
orientation|取向
parameter|参数
participation|参与
perception|感知
phenomenology|现象学
plurality|复数性、多元性
possibility|可能性
prevalence|普遍性
priority|优先性
procedure|程序
proficiency|熟练度
provisionality|暂时性
rationality|理性
rationale|理由、理论基础
relevance|相关性
reliability|可靠性
resilience|韧性
resolution|解决、分辨率
resources|资源
responsiveness|响应性
reversibility|可逆性
rigour|严谨性
scrutiny|审查
significance|重要性
specificity|特异性
stability|稳定性
structure|结构
substance|实质
sustainability|可持续性
threshold|阈值
trajectory|轨迹
transparency|透明度
uncertainty|不确定性
utility|效用
vulnerability|脆弱性
welfare|福祉`,
  4: `
abjection|卑贱、排斥
affectivity|情感性
allegory|寓言
alterity|他异性
ambivalence|矛盾心理
anamnesis|回忆、追忆
antagonism|对抗
arbitrariness|任意性
assemblage|聚合体
axiom|公理
biopolitics|生命政治
canon|经典体系
categorical|范畴的、绝对的
commodification|商品化
commensurability|可通约性
contestation|争议、竞争
contingent|偶然的
counterfactual|反事实的
deconstruction|解构
deference|敬从、遵从
delimitation|界限划定
denaturalise|去自然化
derivative|派生的
determinism|决定论
dialectic|辩证法
discontinuity|不连续性
discursivity|话语性
displacement|置换、迁移
disruption|扰乱
dominant|支配性的
duality|二元性
elision|省略
emergent|新兴的
entrenchment|固化
epistemology|认识论
essentialise|本质化
ethnography|民族志
exclusionary|排斥性的
exegesis|诠释、注释
exogenous|外生的
fallacy|谬误
finitude|有限性
foreground|前景、突出
genealogical|谱系的
hermeneutic|诠释学的
heterodox|异端的、非正统的
historicise|历史化
hybridity|混杂性
immanence|内在性
immanent|内在的
incommensurable|不可通约的
individuation|个体化过程
indeterminacy|不确定性
institutionality|制度性
instrumentality|工具性
interpellation|召唤、质询
intersubjectivity|主体间性
irreducible|不可化约的
irreversibility|不可逆性
liminality|阈限性
materialism|唯物主义
metaphor|隐喻
metonymy|转喻
modernism|现代主义
monism|一元论
normativity|规范性
objectification|客体化
ontology|本体论
orthodoxy|正统观念
overdetermination|多重决定
paradoxical|悖论性的
performativity|施为性
phenomenal|现象的
plurality|多元性
polysemy|多义性
postulate|假定、命题
prescriptive|规定性的
problematise|问题化
procedural|程序性的
provisional|暂时的
rearticulate|重新表述
recontextualise|重新语境化
reification|物化
relativism|相对主义
rendering|呈现、描绘
representation|表征
resistance|抵抗
restitution|恢复、赔偿
rhetoric|修辞
semiology|符号学
signifier|能指
signification|意义生成
singularity|奇异性、单一性
sociality|社会性
structuralism|结构主义
subaltern|弱势从属群体
subversion|颠覆
supplementarity|补充性
symbolic|象征性的
synchronic|共时的
teleological|目的论的
temporality|时间性
totality|总体性
transcendental|先验的
transgression|逾越、违反
ubiquity|无处不在
universalism|普遍主义
verisimilitude|逼真性
viscosity|黏滞性
absolutism|绝对主义
accommodation|调适
actualisation|实现、现实化
adjudication|裁定
agency|能动性
alienation|异化
anomie|失范
appropriation|挪用、占用
artifice|人为构造
ascription|归属
authorial|作者的
autopoiesis|自创生
binary|二元的
bricolage|拼贴、拼装
caesura|停顿、断裂
cartography|制图学
circularity|循环性
citationality|引用性
codification|编纂、编码
collectivity|集体性
coloniality|殖民性
concretisation|具体化
conjuncture|关键时刻、结合
constitutive|构成性的
contiguity|邻接性
counterpoint|对位
decentering|去中心化
decolonial|去殖民的
decontextualise|去语境化
deferral|延异、延缓
denotation|外延意义
dependency|依赖性
deterritorialise|去疆域化
diachronic|历时的
difference|差异
disavowal|否认、拒认
discourse|话语
dislocation|错位
dissemination|播散
embodiment|具身化
enunciation|言说
episteme|知识型
essentialism|本质主义
exteriority|外在性
figuration|形象化
focalisation|聚焦
formation|形成
fragment|碎片
genealogy|谱系
heterogeneity|异质性
historicity|历史性
homology|同源性
identity|身份、同一性
ideology|意识形态
indexicality|指示性
intertextuality|互文性
iteration|重复、迭代
legitimation|合法化
logocentrism|逻各斯中心主义
mediation|中介
metanarrative|元叙事
modalisation|情态化
negativity|否定性
nominalism|唯名论
otherness|他者性
parataxis|并列结构
particularity|特殊性
periphery|边缘
positionality|立场性
presupposition|预设
productivity|生产性
provenance|来源
proximity|接近性
punctum|刺点
recursion|递归
referentiality|指称性
reflexivity|反思性
relationality|关系性
repetition|重复
reterritorialise|再疆域化
rupture|断裂
secularisation|世俗化
sedimentation|沉积、固化
signified|所指
spectrality|幽灵性
specularity|镜像性
subjectivation|主体化
subtext|潜台词
superstructure|上层建筑
synecdoche|提喻
taxonomy|分类学
textuality|文本性
theorisation|理论化
topology|拓扑学
transitivity|及物性
univocity|单义性
valorisation|价值化
virtuality|虚拟性`,
  5: `
abduction|溯因推理
absolutisation|绝对化
acosmism|无世界论
adumbration|勾勒、预示
aletheia|真理的显现
aleatory|偶然的
anacoluthon|句法中断
anastrophe|倒装
anomie|失范
antinomian|反律法的
antithesis|对立命题
apodictic|确凿无疑的
apophasis|否定神学式表达
aporic|充满困境的
archeology|考古学、知识考古
aseity|自因性
autotelic|自足目的的
banality|平庸性
cathexis|情感投注
chiasmus|交错配列
circumscription|限制、界定
coextensive|同延的
constellation|星座式结构
contingency|偶然性
cosmology|宇宙论
deictic|指示性的
demystification|去神秘化
denegation|否认性承认
deontic|道义的
depersonalisation|非人格化
desublimation|去升华
diaeresis|分音、区分
différance|延异
disambiguation|消歧
disenchantment|祛魅
dispositif|装置
doubleness|双重性
doxology|颂赞文
ecceity|此性
eidetic|本质直观的
ellipsis|省略
enantiomorph|镜像异构体
entailment|蕴含
epiphenomenon|附带现象
epoche|悬置判断
equivocity|多义性
erasure|擦除、抹消
eschatology|末世论
essentiality|本质性
eventuality|可能事件
exemplarity|典范性
exteriorisation|外化
factical|事实性的
facticity|事实性
finality|终极目的
foreclosure|排除、封闭
formalism|形式主义
fractality|分形性
generativity|生成性
haecceity|此性、个体性
heterotopia|异托邦
homonymy|同形异义
hyperreality|超真实
hypostasis|实体化、假定实体
iconicity|像似性
idiom|习语
imbrication|交叠、嵌合
individuation|个体化
ineffability|不可言说性
infinitude|无限性
intentionality|意向性
interiority|内在性
interstice|间隙
ipseity|自我性
isomorphism|同构
kenosis|自我虚空
kairos|关键时机
logology|词语学
metalepsis|跨层叙述
metaphysics|形而上学
metonymic|转喻的
mimesis|摹仿
monad|单子
negation|否定
noesis|意向活动
noema|意向对象
nomos|规范、法则
nonidentity|非同一性
nullity|无效、虚无
occlusion|遮蔽
ontic|存在者层面的
originarity|原初性
ostension|指示
overcoding|过度编码
paralogism|谬误推理
paratactic|并列的
peripeteia|突转
perspectivism|视角主义
pharmakon|药物兼毒物
physis|自然、本性
plurivocity|多声性
poiesis|创制、生成
polyphony|复调
positivity|肯定性
prefiguration|预构
prelinguistic|前语言的
presentism|现在主义
proleptic|预示性的
prosopopoeia|拟人修辞
psychologism|心理主义
quiddity|何性、本质
reification|物化
remainder|剩余
reterritorialisation|再疆域化
rhizome|根茎
schematism|图式论
sediment|沉积物、沉淀
semiosis|符号过程
simulacral|拟像的
singularisation|奇异化
solipsism|唯我论
spectral|幽灵般的
subalternity|从属地位
sublation|扬弃
subreption|偷换概念
supplement|补充物
syncretism|融合主义
syntagm|组合关系
tautological|同义反复的
teleonomy|目的性结构
telos|目的
theodicy|神义论
topos|母题、场所
transcendence|超越性
transcendentalism|先验主义
transvaluation|价值重估
univocal|单义的
unrepresentable|不可表征的
veridical|真实的
virtual|虚拟的
worldhood|世界性
zeugma|轭式修辞
abnegation|自我否弃
absorption|吸收、专注
actuality|现实性
adjudicative|裁决性的
affordance|可供性
agonism|竞争性对抗
altercation|争吵
ambit|范围
anarchic|无政府的
anteriority|先在性
antinomies|二律背反
aporetic|疑难的
appresentation|共现
archetypal|原型的
asceticism|禁欲主义
assimilation|同化
asymptotic|渐近的
attributional|归因的
authorisation|授权
autonomy|自主性
becoming|生成
bifurcation|分叉
bracketing|悬置
canonisation|经典化
categoricity|范畴性
causation|因果作用
chora|空间、容器
codetermination|共同决定
coherence|连贯性
collectivisation|集体化
compossibility|共可能性
concealment|遮蔽
concretum|具体实体
connotation|内涵
consilience|融贯
constitutivity|构成性
constructivism|建构主义
contiguity|相邻性
counterfinality|反目的性
cryptonymy|隐名性
decomposition|分解
deconstructionist|解构主义者
dedifferentiation|去分化
defamiliarisation|陌生化
delegitimation|去合法化
demarcation|划界
denaturalisation|去自然化
denotation|外延
deracination|去根性
derivation|派生
desire|欲望
determinacy|确定性
deterritorialisation|去疆域化
diachrony|历时性
dialectical|辩证的
discontinuity|断裂性
discursiveness|话语性
disidentification|去认同
disjunction|分离
dislocation|错位
displacement|替换、移位
dissemination|播散
dominance|支配
doublebind|双重束缚
ecology|生态学
economy|经济、节约
effectuation|实现
emplacement|安置、定位
enfoldment|卷入、折叠
enunciation|言说
epistemology|认识论
equivalence|等价
eventness|事件性
exclusion|排除
exemplification|例证
exteriority|外在性
figuration|形象化
finitude|有限性
formlessness|无形式性
genealogy|谱系
generalizability|可推广性
groundlessness|无根基性
hermeneutics|诠释学
heterogeneity|异质性
historicity|历史性
homogeneity|同质性
hybridity|混杂性
idealism|唯心主义
identity|同一性、身份
immanence|内在性
indeterminacy|不确定性
indexicality|指示性
individuation|个体化
intersubjectivity|主体间性
irreversibility|不可逆性
iteration|重复
juxtaposition|并置
legitimacy|正当性
liminality|阈限性
materiality|物质性
mediation|中介
metanarrative|元叙事
modernity|现代性
modality|情态
monism|一元论
negativity|否定性
nominalism|唯名论
normativity|规范性
ontology|本体论
otherness|他者性
paradigm|范式
performativity|施为性
phenomenology|现象学
pluralism|多元主义
positionality|立场性
presupposition|预设
provenance|来源
qualia|感质
rationality|理性
reciprocity|互惠
recursion|递归
reductionism|还原主义
reflexivity|反思性
relationality|关系性
representation|表征
resistance|抵抗
reterritorialise|再疆域化
reversibility|可逆性
rhetoric|修辞
semiotics|符号学
singularity|奇异性
sociality|社会性
sovereignty|主权
subjectivity|主观性
subversion|颠覆
superstructure|上层建筑
symbolism|象征主义
synthesis|综合
teleology|目的论
temporality|时间性
textuality|文本性
theory|理论
totality|总体性
transgression|逾越
triangulation|三角互证
typology|类型学
universality|普遍性
univocity|单义性
validity|有效性
verisimilitude|逼真性
virtuality|虚拟性
volatility|易变性
weltanschauung|世界观
accretionary|增积的
adventitious|偶然附带的
affectation|矫饰
agential|能动者的
allegorical|寓言性的
allochronic|异时的
anagnorisis|发现、认知转折
anaphora|首语重复
anastomosis|连接、吻合
anomic|失范的
anthropocentric|人类中心主义的
antinomy|二律背反
aporia|难题、困境
aporetic|疑难的
archival|档案的
archetypal|原型的
artifactual|人工制品的
ascription|归属
associative|联想性的
atemporal|非时间性的
autarky|自给自足
autopoietic|自创生的
axiomatic|公理性的
baroque|巴洛克式的、繁复的
behaviouralism|行为主义
biopower|生命权力
bracketing|悬置判断
calculus|微积分、计算体系
canonical|经典的、规范的
categorisation|范畴化
chora|空间、容器
chronotope|时空体
codetermination|共同决定
coimplication|共同蕴含
compossibility|共可能性
conatus|自我保存的努力
concretum|具体实体
consubstantial|同质同体的
constructivist|建构主义的
corporeality|身体性
counterfinality|反目的性
cryptic|隐秘难懂的
decentred|去中心的
deconstructionist|解构主义的
dedifferentiation|去分化
defamiliarisation|陌生化
delegitimation|去合法化
demarcative|划界的
denaturalisation|去自然化
deracination|去根性
desire|欲望
determinacy|确定性
diacritic|区别性的
diachrony|历时性
dialogism|对话主义
diffuse|扩散的、模糊的
digitality|数字性
disavowal|否认、拒认
disidentification|去认同
disjunctive|分离性的
dispositional|倾向性的
doublebind|双重束缚
ecocriticism|生态批评
ecological|生态的
economisation|经济化
effectuation|实现、落实
eidolon|影像、幻象
embodied|具身的
emplacement|安置、定位
enfoldment|卷入、折叠
enunciative|言说的
epistemological|认识论的
equivocality|多义性
eventness|事件性
exemplification|例证
exoteric|公开的、通俗的
factitious|人为的、虚假的
figural|形象的
forclusion|排除、封闭
formlessness|无形式性
generative|生成性的
genericity|一般性
geopolitical|地缘政治的
groundlessness|无根基性
habitus|惯习
heteroglossia|众声喧哗
heuristics|启发法
holism|整体论
hyperobject|超物体
hypotaxis|主从结构
iconoclasm|破坏偶像
idealisation|理想化
immanentise|使内在化
impersonality|非人格性
incorporeal|非物质的
indexical|指示性的
individuated|个体化的
induction|归纳
infrastructural|基础设施的
inherence|内在归属
intersubjective|主体间的
irony|反讽
isotopy|同位性
iterability|可重复性
juridical|法律的
kinship|亲属关系
legibility|可读性、可辨识性
lexical|词汇的
locality|地方性
logocentric|逻各斯中心的
macrocosm|宏观世界
materialise|物质化
metacritical|元批评的
metonymical|转喻性的
microphysics|微观物理学
modal|情态的
monological|独白式的
multivocal|多声部的
mythopoetic|神话诗学的
necropolitics|死亡政治
neologism|新词
nomological|规律性的
nonlinear|非线性的
nonrepresentational|非表征的
objectual|物件的
ontogenesis|个体发生
orthogonal|正交的
overcoding|过度编码
palimpsest|重写本
panopticism|全景敞视主义
paradigmatic|范式性的
parallax|视差
parergon|附属物、框外物
perception|感知
performativity|施为性
perichoresis|互渗、共在
phenomenalisation|现象化
philosopheme|哲学概念单元
phoronomy|运动理论
pluralisation|多元化
poetic|诗性的
politicality|政治性
polycentric|多中心的
precarity|不稳定状态
predication|述谓
prelinguistic|前语言的
presencing|呈现、临在
problematics|问题域
processual|过程性的
proprioception|本体感觉
proxemics|空间关系学
punctuation|标点、断句
qualitative|定性的
quantification|量化
quasi|准、近似
quotidian|日常的
reification|物化
relational|关系性的
remediation|再媒介化
repetition|重复
resignification|重新赋义
rhizomatic|根茎式的
ritualisation|仪式化
schematic|图式的
securitisation|安全化
semiosphere|符号圈
seriality|序列性
signifying|表意的
similitude|相似性
socialisation|社会化
spatiality|空间性
speciation|物种形成
structuration|结构化
subalternity|从属地位
subsumption|归摄
supervenience|随附性
syntagmatic|组合关系的
technicity|技术性
temporisation|时间化、延宕
territoriality|疆域性
thematise|主题化
thingness|物性
totalisation|总体化
traceability|可追溯性
transduction|转换、传导
translatability|可译性
transversality|横向贯通性
unfolding|展开
universalisation|普遍化
unmarked|无标记的
veridiction|真理陈述
vitalism|生命力论
vocality|声音性
worlding|世界化
zeitgeist|时代精神
`};

function parseEntries(source) {
  return source.trim().split("\n").filter((line) => line.trim()).map((line) => {
    const [termContent, ...meaningParts] = line.trim().split("|");
    return { termContent, meaning: meaningParts.join("|") };
  });
}

async function main() {
  await database.initializeDatabase();
  const existingTerms = await database.all("SELECT termContent FROM aussieTerms");
  const seen = new Set(existingTerms.map(({ termContent }) => termContent.trim().toLocaleLowerCase("en-AU")));
  const additions = [];

  for (const [levelText, source] of Object.entries(wordBanks)) {
    const level = Number(levelText);
    const fallbackSources = {
      3: [wordBanks[4]],
      4: [wordBanks[5]],
      5: [wordBanks[4], wordBanks[3]]
    };
    const entries = parseEntries([source, ...(fallbackSources[level] || [])].join("\n"));
    let addedForLevel = 0;
    for (const entry of entries) {
      if (!entry.termContent || !entry.meaning) {
        throw new Error(`Level ${level} contains an invalid entry: ${entry.termContent || "(missing term)"}`);
      }
      const normalized = entry.termContent.toLocaleLowerCase("en-AU");
      if (seen.has(normalized)) {
        continue;
      }
      seen.add(normalized);
      additions.push({ ...entry, level });
      addedForLevel += 1;
      if (addedForLevel === 200) {
        break;
      }
    }

    if (addedForLevel !== 200) {
      throw new Error(`Level ${level} has only ${addedForLevel} usable non-duplicate words.`);
    }
  }

  await database.run("BEGIN IMMEDIATE TRANSACTION");
  try {
    for (const term of additions) {
      await database.run(
        `INSERT INTO aussieTerms (termContent, meaning, example, termType, level)
         VALUES (?, ?, '', 'word', ?)`,
        [term.termContent, term.meaning, term.level]
      );
    }
    await database.run("COMMIT");
  } catch (error) {
    await database.run("ROLLBACK");
    throw error;
  }

  console.log(`Added ${additions.length} words: 200 words for each level.`);
}

main()
  .catch((error) => {
    console.error(error.message);
    process.exitCode = 1;
  })
  .finally(() => database.close());
