const database = require("../db");

// 备选词库已经大幅扩充，确保去重后依然能取足 200 个词
const wordBanks = {
  1: `
accept|接受
access|访问、入口
accident|事故
accompany|陪伴
account|账户、解释
accuracy|准确性
custom|风俗、习惯
damage|损坏
danger|危险
deal|处理、交易
debt|债务
decay|腐烂、衰退
deceive|欺骗
decide|决定
decision|决定
declare|宣布
decorate|装饰
decrease|减少
dedicate|奉献
deep|深的
defeat|击败
defend|保卫
defense|防御
deficit|赤字
degree|程度、学位
delay|延迟
delegate|代表
delete|删除
deliberate|故意的
delicate|精致的、脆弱的
deliver|交付
demand|需求
democracy|民主
demonstrate|证明、示威
dense|密集的
department|部门
depend|依赖
deposit|存款、沉积
depress|使沮丧
deprive|剥夺
descend|下降
describe|描述
desert|沙漠、抛弃
deserve|值得
design|设计
desire|渴望
despair|绝望
despite|尽管
destroy|破坏
detail|细节
determine|决定
develop|发展
devote|致力于
diagnose|诊断
dictate|口授、命令
differ|不同
difficult|困难的
digital|数字的
dignity|尊严
dilemma|困境
direct|直接的、指导
disable|使残疾
disadvantage|劣势
disagree|不同意
disappear|消失
disappoint|使失望
disaster|灾难
discard|丢弃
discipline|纪律、学科
disclose|揭露
discount|折扣
discover|发现
discriminate|歧视
discuss|讨论
disease|疾病
disgrace|耻辱
disgust|厌恶
dismiss|解雇
display|显示
dispute|争端
dissolve|溶解
distance|距离
distinguish|区分
distract|分心
distribute|分配
district|地区
disturb|打扰
divide|划分
document|文件
donate|捐赠
doubt|怀疑
drastic|猛烈的
draw|画、吸引
dream|梦想
dress|穿衣、裙子
drill|钻孔、训练
drink|喝、饮料
drive|驾驶、驱动
drop|掉落、滴
drug|药物、毒品
dual|双重的
dull|迟钝的、枯燥的
dump|倾倒
duplicate|复制
durable|耐用的
duty|责任
eager|渴望的
earn|赚取
earnest|认真的
ease|减轻、舒适
echo|回声
ecology|生态学
economic|经济的
edge|边缘
educate|教育
effect|效果、影响
efficiency|效率
effort|努力
eject|弹出
elaborate|详细说明
elastic|有弹性的
elect|选举
elegant|优雅的
elevate|提升
eligible|有资格的
eliminate|消除
elite|精英
embarrass|使尴尬
embassy|大使馆
embed|嵌入
emotion|情绪
empire|帝国
employ|雇佣
empty|空的
emulate|模仿、赶超
enclose|附上、包围
encounter|遭遇
encourage|鼓励
encyclopedia|百科全书
endless|无止境的
endorse|认可、背书
endow|赋予
endure|忍受
energy|能量
enhance|增强
enjoy|享受
enlarge|扩大
enormous|巨大的
enquire|询问
enrich|使丰富
enroll|登记、注册
entail|牵涉、需要
enter|进入
enterprise|企业
entertain|娱乐
enthusiasm|热情
entire|整个的
entitle|赋予权利
entrance|入口
entreat|恳求
envelope|信封
environment|环境
envy|嫉妒
episode|插曲、剧集
equal|平等的
equation|方程式
equivalent|相等的
era|时代
erase|擦除
error|错误
erupt|爆发
escape|逃跑
escort|护送
essay|散文、论文
essence|本质
essential|必不可少的
establish|建立
estate|房地产
eternal|永恒的
evaluate|评估
evaporate|蒸发
event|事件
eventual|最终的
evident|明显的
evil|邪恶的
exact|准确的
exaggerate|夸大
examine|检查
exceed|超过
excel|擅长
excellent|优秀的
except|除了
excess|过量
exchange|交换
excite|使兴奋
exclaim|呼喊
exclude|排除
exclusive|独有的
execute|执行
executive|行政人员
exercise|锻炼
exert|施加
exhaust|耗尽
exhibit|展览
exile|流放
exist|存在
exit|出口
expand|扩张
expect|期望
expense|花费
expensive|昂贵的
experience|经验
experiment|实验
expire|到期
explain|解释
explode|爆炸
exploit|开发、剥削
explore|探索
export|出口
expose|暴露
express|表达
extend|延伸
extensive|广泛的
extent|程度
exterior|外部的
external|外部的
extinct|灭绝的
extra|额外的
extract|提取
extreme|极端的
fabric|织物、结构
face|面对、脸
facility|设施
fact|事实
factor|因素
factory|工厂
fade|褪色、逐渐消失
fail|失败
faint|微弱的、晕倒
fair|公平的
faith|信仰
false|错误的
familiar|熟悉的
famous|著名的
fan|风扇、粉丝
fancy|想象、华丽的
fantastic|极好的
fare|票价
fascinate|使着迷
fashion|时尚
fasten|系紧
fatal|致命的
fate|命运
fault|过错
favor|好意
fear|害怕
feast|盛宴
feature|特征
federal|联邦的
fee|费用
feeble|虚弱的
feed|喂养
feel|感觉
fellow|同伴
female|女性的
fence|栅栏
fertile|肥沃的
festival|节日
fetch|去取
fever|发烧
few|很少
fiber|纤维
fiction|小说
field|田野、领域
fierce|凶猛的
fight|战斗
figure|数字、人物
file|文件
fill|装满
film|电影
filter|过滤
final|最终的
finance|金融
find|寻找
fine|好的、罚款
finger|手指
finish|完成
fire|火、解雇
firm|坚定的、公司
first|第一
fish|鱼
fit|适合
fix|固定、修理
flag|旗帜
flame|火焰
flash|闪光
flat|平坦的
flavor|味道
flaw|瑕疵
flee|逃跑
flesh|肉
flexible|灵活的
flight|飞行
float|漂浮
flock|群
flood|洪水
floor|地板
flour|面粉
flourish|繁荣
flow|流动
flower|花
flu|流感
fluctuate|波动
fluent|流利的
fluid|流体
fly|飞
focus|焦点
fog|雾
fold|折叠
folk|人们
follow|跟随
fond|喜欢的`,
  2: `
abdicate|退位、放弃
aberrant|异常的
abeyance|中止、搁置
abjure|发誓放弃
abscond|潜逃
abstemious|有节制的
abstruse|深奥的
abysmal|极糟的、深不可测的
accretion|逐渐增加
acerbic|尖酸的
acquiesce|默许
acrimony|尖刻、毒辣
acumen|敏锐、聪明
adamant|固执的、坚定的
admonish|警告、责备
adroit|熟练的、机敏的
adulation|奉承
adulterate|掺假
aesthetic|审美的
affable|和蔼可亲的
aggrandize|增加、夸大
alacrity|敏捷、乐意
alleviate|减轻、缓解
amalgamate|合并
ameliorate|改善
amenable|顺从的
anachronism|时代错置
analogous|类似的
anarchy|无政府状态
anomaly|异常
antagonize|使敌对
apathy|冷漠
apocryphal|伪造的
appease|安抚
apposite|适当的
appropriate|挪用、适当的
arcane|神秘的、难懂的
archaic|古老的
arduous|艰巨的
articulate|清晰地表达
ascetic|苦行的
asperity|严酷、粗暴
assuage|平息、缓和
astringent|严厉的、收敛的
audacious|大胆的
augment|增加
austere|简朴的、严厉的
avarice|贪婪
aver|断言
banal|平庸的
belie|掩饰、证明为假
beneficent|仁慈的
bombastic|夸夸其谈的
boorish|粗野的
burgeon|迅速生长
burnish|擦亮
cacophony|刺耳的声音
calumny|诽谤
capricious|反复无常的
castigate|严惩
catalyst|催化剂
caustic|腐蚀性的、刻薄的
chicanery|欺骗
coagulate|凝结
coda|尾声
cogent|有说服力的
commensurate|相称的
compendium|摘要
complaisant|顺从的
compliant|顺从的
conciliatory|抚慰的
condone|宽恕
confound|使混淆
connoisseur|鉴赏家
contention|争论
contentious|好争吵的
contrite|悔罪的
conundrum|谜题
converge|汇聚
convoluted|复杂的
craven|怯懦的
credulous|轻信的
crescendo|渐强
decorum|端庄、得体
default|违约、拖欠
deference|尊崇、顺从
delineate|描绘
denigrate|诋毁
deride|嘲笑
derivative|派生的
desiccate|使干枯
desultory|散漫的
deterrent|威慑物
diatribe|长篇抨击
dichotomy|二分法
diffidence|缺乏自信
diffuse|散播、冗长的
digression|离题
dirge|挽歌
disabuse|使醒悟
discerning|有洞察力的
discordant|不和谐的
discredit|使丧失信誉
discrepancy|差异
discrete|分离的
disingenuous|不真诚的
disinterested|无私的、公正的
disjointed|脱节的
dismiss|解雇、不予考虑
disparage|贬低
disparate|迥然不同的
dissemble|掩饰
disseminate|传播
dissolution|解散、溶解
dissonance|不和谐
distend|膨胀
distill|蒸馏、提取精华
diverge|分歧
divest|剥夺
dogmatic|武断的
dormant|休眠的
dupe|欺骗、易受骗者
ebullient|热情洋溢的
eclectic|兼收并蓄的
efficacy|功效
effrontery|厚颜无耻
elegy|挽歌
elicit|引出
embellish|装饰
empirical|经验主义的
emulate|效仿
endemic|地方性的
enervate|使衰弱
engender|产生
enhance|提高
enigma|谜
ephemeral|短暂的
equanimity|镇定
equivocate|模棱两可地说
erudite|博学的
esoteric|深奥的
eulogy|颂词
euphemism|委婉语
exacerbate|加剧
exculpate|开脱罪责
exigency|紧急情况
extrapolation|推断
facetious|爱开玩笑的
facilitate|促进
fallacious|谬误的
fatuous|愚笨的
fawning|奉承的
felicitous|恰当的
fervor|热情
flag|衰退
fledgling|无经验的人
flout|公然藐视
foment|煽动
forestall|预先阻止
frugality|节俭
futile|徒劳的
gainsay|否认
garrulous|喋喋不休的
goad|刺激
gouge|欺诈、勒索
grandiloquent|夸张的
gregarious|合群的
guileless|厚道的、诚实的
gullible|易受骗的
harangue|长篇大论的演说
homogeneous|同质的
hyperbole|夸张
iconoclast|反传统者
idolatry|偶像崇拜
immutable|不可变的
impair|损害
impassive|冷漠的
impede|阻碍
impermeable|不可渗透的
imperturbable|沉着的
impervious|不受影响的
implacable|无法平息的
implicit|含蓄的
implode|内爆
inadvertently|不经意地
inchoate|早期的、未充分发展的
incongruity|不一致
inconsequential|不重要的
incorporate|合并
indeterminate|不确定的
indigence|贫困
indolent|懒惰的
inert|惰性的
ingenuous|天真的
inherent|固有的
innocuous|无害的
insensible|无知觉的
insinuate|暗示
insipid|乏味的
insularity|狭隘
intractable|棘手的
intransigence|不妥协
inundate|淹没
inured|习惯的
invective|谩骂
irascible|易怒的
irresolute|犹豫不决的
itinerary|行程
laconic|简洁的
lassitude|疲乏
latent|潜在的
laud|赞美
lethargic|昏睡的
levee|堤坝
levity|轻浮
loquacious|多话的
lucid|明晰的
luminous|发光的
magnanimity|宽宏大量
malingerer|装病逃避工作者
malleable|可塑的
maverick|特立独行者
mendacious|虚假的
metamorphosis|变形
meticulous|一丝不苟的
misanthrope|厌恶人类者
mitigate|减轻
mollify|平息
morose|郁闷的
negate|否定
neophyte|新手
nexus|核心、联系
noisome|恶臭的
nonchalant|冷淡的
nostalgia|怀旧
novice|新手
nuance|细微差别
nullify|使无效
obdurate|固执的
obfuscate|使模糊
objective|客观的
oblique|斜的、拐弯抹角的
obliterate|抹除
obscure|模糊的
obsequious|奉承的
obsolete|废弃的
obstinate|固执的
obstreperous|吵闹的
obviate|排除
occlude|封闭
odious|可憎的
officious|多管闲事的
ominous|不详的
onerous|繁重的
opaque|不透明的
opprobrium|耻辱
opulence|富裕
oscillate|振荡
ostentatious|炫耀的
ostracize|放逐
pacify|安抚
painstaking|煞费苦心的
palliate|减轻
palpable|可触知的
panacea|万能药
paradigm|范例
paradox|悖论
paragon|模范
paramount|首要的
pariah|贱民
parochial|狭隘的
parody|拙劣的模仿
parsimony|吝啬
partisan|党派的
patent|专利、明显的
pathology|病理学
paucity|缺乏
pedantic|迂腐的
pedestrian|平庸的
pejorative|贬义的
pellucid|清澈的
penchant|倾向
penitent|忏悔的
penury|贫困
perceptive|敏锐的
perfunctory|敷衍的
perilous|危险的
peripatetic|漫游的
peripheral|外围的
permeate|渗透
pernicious|有害的
perpetual|永久的
perspicacious|有洞察力的
pervasive|普遍的
petulant|暴躁的
philanthropy|慈善
phlegmatic|冷淡的
pivotal|关键的
placate|安抚
placid|平静的
plasticity|可塑性
platitude|陈词滥调
plethora|过量
pliable|易弯的
plummet|垂直落下
polarize|使两极分化
polemical|好争论的
pragmatic|务实的
prattle|闲扯
precarious|危险的
precipitate|促成、鲁莽的
preclude|阻止
precocious|早熟的
predilection|偏好
preeminent|卓越的
prescient|有预知能力的
presumptuous|专横的
prevaricate|支吾
pristine|原始的
probity|诚实
proclivity|倾向
prodigal|挥霍的
prodigious|巨大的
profligate|挥霍的
profound|深刻的
profuse|丰富的
proliferate|激增
prolific|多产的
propensity|倾向
propitiate|抚慰
propriety|得体`,
  3: `
abductive|溯因的
absolutism|绝对主义
abstractive|抽象的
accelerationism|加速主义
accretionary|增积的
actant|行动素
actualization|现实化
adjudication|裁决
advection|平流
adumbration|预示、勾画
affinal|姻亲的
agglomeration|结块、聚集
agnosticism|不可知论
alienation|异化
allometric|异速生长的
allopatric|异域分布的
amensalism|偏害共生
amniotic|羊膜的
anabolism|合成代谢
anacrusis|弱起
anastomosis|吻合术
anatomical|解剖的
androcentric|男性中心的
angiogenesis|血管生成
animism|万物有灵论
anisotropy|各向异性
anomalous|异常的
anomie|失范
antagonism|对抗
anthropocentric|人类中心的
anthropomorphic|拟人的
antibody|抗体
anticline|背斜
antigen|抗原
antinomy|二律背反
apathetic|冷漠的
aperture|孔径
aphasia|失语症
aphelion|远日点
aphotic|无光的
apoptosis|细胞凋亡
apraxia|失用症
arbitrage|套利
archetype|原型
assimilation|同化
asymptote|渐近线
atavism|返祖现象
attenuation|衰减
attributional|归因的
autecology|个体生态学
autocracy|独裁
autoethnography|自我民族志
automaton|自动机
autonomic|自主的
autotrophy|自养
axiology|价值论
axiom|公理
baseline|基线
behaviorism|行为主义
bifurcation|分叉
biocenosis|生物群落
biocentrism|生物中心主义
biogenesis|生物发生
biolith|生物岩
biomechanics|生物力学
biometry|生物统计学
biostratigraphy|生物地层学
biota|生物区系
bivalent|二价的
bivariable|双变量的
bivariant|双变度的
botulism|肉毒杆菌中毒
bracketing|悬置
bremsstrahlung|韧致辐射
bureaucracy|官僚机构
bycatch|兼捕
calculus|微积分
calorimetry|量热学
capitalism|资本主义
capillarity|毛细现象
catabolism|分解代谢
catalysis|催化作用
cation|阳离子
causality|因果关系
cellation|细胞形成
centromere|着丝粒
centrosome|中心体
cephalization|头化
characterization|表征
chemisorption|化学吸附
chemotaxis|趋化性
chimera|嵌合体
chromatid|染色单体
chromatin|染色质
chromatography|色谱法
chromosome|染色体
chronostratigraphy|年代地层学
circumscription|界限
clade|演化支
cladistics|支序分类学
cladogram|支序图
cleavage|卵裂
climax|演替顶极
cline|渐变群
clonality|克隆性
coalescence|溯祖
codon|密码子
coefficient|系数
coevolution|协同进化
cognition|认知
collinearity|共线性
commensalism|偏利共生
commodification|商品化
communism|共产主义
commutation|交换
compartmentalization|区室化
competition|竞争
complementarity|互补性
computation|计算
concatenation|级联
concentration|浓度
conceptualization|概念化
condensation|冷凝
conductance|电导
configuration|构型
congruence|同余
conjugacy|共轭性
conifer|针叶树
connotation|内涵
consanguinity|血亲
consensus|共识
consequentialism|后果主义
conservatism|保守主义
consilience|融贯
constructivism|建构主义
consumption|消费
contiguity|邻近性
contingency|偶然性
continuum|连续体
convection|对流
convergence|趋同
coordinates|坐标
copula|系词
corollary|推论
corpuscular|微粒的
correlation|相关性
corroboration|确证
cortex|皮层
cosmology|宇宙学
cotyledon|子叶
covalence|共价
covariance|协方差
covariate|协变量
craton|克拉通
creolization|克里奥尔化
criticality|临界状态
crystallography|结晶学
cultigen|栽培种
cybernetics|控制论
cytokinesis|胞质分裂
cytology|细胞学
cytoplasm|细胞质
darwinism|达尔文主义
deamination|脱氨作用
decalcification|脱钙
deceleration|减速
decentralization|去中心化
decimation|大规模毁灭
deconstruction|解构
deduction|演绎
defaunation|动物区系破坏
deflation|通货紧缩
defoliation|落叶
deforestation|森林砍伐
deglaciation|冰川退缩
degradation|降解
deindustrialization|去工业化
deism|自然神论
delegation|授权
deletion|缺失
demagogue|煽动者
demarcation|划界
demecology|种群生态学
democracy|民主
demography|人口学
demyelination|脱髓鞘
denaturalization|去自然化
dendrochronology|树木年代学
denitrification|反硝化作用
denotation|外延
deontology|义务论
depopulation|人口减少
depolarization|去极化
deregulation|放松管制
derivative|导数、衍生物
dermatitis|皮炎
desalination|脱盐
desiccation|干燥
desorption|解吸
determinism|决定论
detritivore|食碎屑动物
devaluation|贬值
diagenesis|成岩作用
diagnosis|诊断
dialectic|辩证法
diapause|滞育
diaspora|流散
diastrophism|地壳运动
diathesis|素质
dichotomy|二分法
dicotyledon|双子叶植物
dielectric|电介质
differentiation|分化
diffraction|衍射
diffusion|扩散
dimorphism|二态性
diode|二极管
dioecious|雌雄异株的
diploid|二倍体
dipole|偶极子
dipsomania|烧酒狂
directional|定向的
disaggregation|解聚
disambiguation|消歧
disassimilation|异化作用
disclimax|偏途顶极
discourse|话语
disease|疾病
disequilibrium|不平衡
disjunction|分离
dislocation|位错
dispersal|扩散
dispersion|色散
displacement|位移
disposition|倾向
disruption|破裂
dissemination|播散
dissipation|耗散
dissociation|解离
dissonance|失调
distal|远端的
distillation|蒸馏
distribution|分布
disturbance|干扰
divergence|散度
diversification|多样化
diversity|多样性
docility|温顺
doctrine|教义
dogma|教条
domestication|驯化
dominance|优势度
dormancy|休眠
dosimetry|剂量学
downwelling|下涌
drosophila|果蝇
dualism|二元论
duopoly|双头垄断
dysplasia|发育不良
ecesis|定居(生态)
echolocation|回声定位
ecliptic|黄道
ecotone|群落交错区
ecotype|生态型
ectoderm|外胚层
edaphic|土壤的
egalitarianism|平等主义
eigenvalue|特征值
elasmobranch|板鳃鱼类
electrolyte|电解质
electromagnetism|电磁学
electrophoresis|电泳
electrostatics|静电学
embryology|胚胎学
emissivity|发射率
empiricism|经验主义
emulsion|乳浊液
enantiomer|对映异构体
endemicity|地方性
endergonic|吸能的
endocardium|心内膜
endocrine|内分泌
endocytosis|胞吞作用
endoderm|内胚层
endogenous|内源的
endophyte|内生菌
endoplasmic|内质的
endosperm|胚乳
endothermic|吸热的
endotoxin|内毒素
entomology|昆虫学
entrainment|夹带
entropy|熵
enzyme|酶
epicenter|震中
epidemiology|流行病学
epigenetics|表观遗传学
epigraphy|金石学
epilimnion|变温层
epiphyte|附生植物
epistemology|认识论
epithelium|上皮组织
epitope|抗原表位
equilibrium|平衡
equinox|二分点
ergonomics|人类工程学
erosion|侵蚀
erythrocyte|红细胞
escarpment|悬崖
estuary|河口
ethnocentrism|民族中心主义
ethnography|民族志
ethology|动物行为学
etiology|病因学
eukaryote|真核生物
eutrophication|富营养化
evapotranspiration|蒸散
evolution|进化
excitability|兴奋性
excretion|排泄
exergonic|放能的
exocytosis|胞吐作用
exogenous|外源的
exon|外显子
exosphere|外逸层
exothermic|放热的
exotoxin|外毒素
experimentation|实验
extinction|灭绝
extrapolation|外推法
facies|相
fascism|法西斯主义
faulting|断层作用
fecundity|繁殖力
feldspar|长石
feminism|女性主义
fermentation|发酵
ferromagnetism|铁磁性
fertility|肥力、生育力
feudalism|封建主义
fibrinogen|纤维蛋白原
fibroblast|成纤维细胞
kinematics|运动学
karyotype|核型
jurisprudence|法学
isotope|同位素
isomer|异构体`,
  4: `
achronological|非按时间顺序的
acrolect|上层方言
actantial|行动素的
adstratum|底层语言影响
aestheticism|唯美主义
affectation|矫揉造作
afrofuturism|非洲未来主义
alibi|不在场证明、托辞
alienation|异化
allegorization|寓言化
alliteration|头韵
allusion|典故、暗指
alterity|他异性
ambivalence|矛盾心理
anachronism|时代错置
anagnorisis|发现、顿悟
analepsis|闪回
anaphora|首语重复
androgyny|雌雄同体
animism|万物有灵论
antagonist|反派角色
anthropocene|人类世
anthropomorphism|拟人论
anticlimax|突降法
antihero|反英雄
antiquarianism|好古癖
antithesis|对立、对照
apocalyptic|末世论的
apocrypha|伪经
apologia|辩护文
aporia|疑难、困境
apostrophe|顿呼
appropriation|挪用
archaism|古语
archetype|原型
aside|旁白
assonance|类韵
asyndeton|连词省略
auratic|灵光的
authorial|作者的
autobiography|自传
autodiegetic|自我叙述的
auto-fiction|自传体小说
avant-garde|先锋派
bardic|吟游诗人的
baroque|巴洛克的
bathos|突降、陈腐
bildungsroman|成长小说
biopolitics|生命政治
blank-verse|无韵诗
bombast|浮夸的言辞
bowdlerization|删改
burlesque|滑稽模仿
cacophony|刺耳音
cadence|抑扬顿挫
caesura|休止、停顿
camp|坎普风、造作
canon|正典
carnivalesque|狂欢化的
catachresis|滥用词
catalexis|尾音省略
catharsis|情感净化
characterization|人物塑造
chiasmus|交叉配列法
chronotope|时空体
circumlocution|迂回说法
classicism|古典主义
cliché|陈词滥调
climax|高潮
closure|结尾、闭合
codex|手抄本
colonialism|殖民主义
comedy|喜剧
comic-relief|喜剧救场
conceit|奇思妙想、夸饰
confessional|自白派的
connotation|内涵
consonance|辅音韵
constructivism|建构主义
contextualism|语境主义
convention|惯例
couplet|对句
cubism|立体主义
cyberpunk|赛博朋克
dactyl|扬抑抑格
dadaism|达达主义
decadence|颓废派
decolonization|去殖民化
deconstruction|解构
defamiliarization|陌生化
deictic|指示的
denotation|外延
denouement|结局
descriptive|描写的
detective|侦探的
determinism|决定论
deus-ex-machina|机械降神
dialogic|对话的
diction|措辞
didactic|说教的
diegesis|叙述、讲述
différance|延异
dimeter|二步格
dirge|挽歌
discourse|话语
dissonance|不和谐音
doggerel|打油诗
domesticity|家庭生活
doppelgänger|二重身
drama|戏剧
dramatic-monologue|戏剧独白
dramatis-personae|剧中人物
dystopia|反乌托邦
ecocriticism|生态批评
ecriture|书写
elegy|挽歌
elision|元音省略
ellipsis|省略
empathy|共情
empiricism|经验主义
end-stopped|句末停顿的
enjambment|跨行连续
enlightenment|启蒙运动
epic|史诗
epigram|警句
epigraph|题词
epilogue|跋、尾声
epiphany|顿悟
episteme|知识型
epistolary|书信体的
epitaph|墓志铭
epithalamion|贺婚诗
epithet|表述词
eponym|齐名物
eschatology|末世论
essay|散文、随笔
essentialism|本质主义
estrangement|疏离
euphemism|委婉语
euphony|悦耳之音
eurocentrism|欧洲中心主义
existentialism|存在主义
exegesis|诠释
exemplum|例证
existential|存在的
exordium|开场白
exposition|背景交代
expressionism|表现主义
extra-diegetic|叙事外的
fable|寓言
fabliau|市井故事诗
fabula|故事材料
fairy-tale|童话
fallacy|谬见
fantasy|奇幻
farce|闹剧
feminism|女性主义
fetishism|拜物教
fiction|虚构小说
figuration|形象化
figure-of-speech|修辞格
fin-de-siècle|世纪末
first-person|第一人称
flashback|闪回
flat-character|扁平人物
focalization|聚焦
folio|对折本
folklore|民间传说
foot|音步
foreshadowing|伏笔
formalism|形式主义
frame-narrative|框架叙事
free-indirect-discourse|自由间接引语
free-verse|自由诗
futurism|未来主义
gender|社会性别
genealogy|谱系学
genre|体裁
georgic|田园诗
gothic|哥特式
grand-narrative|宏大叙事
graphic-novel|图像小说
grotesque|怪诞
haiku|俳句
hamartia|悲剧性弱点
hegemony|霸权
hermeneutics|诠释学
hero|主人公
heroic-couplet|英雄双行体
heteroglossia|众声喧哗
heterotopia|异托邦
hexameter|六步格
historical-fiction|历史小说
historicism|历史主义
historiography|历史编纂学
homodiegetic|同叙事层的
homology|同源性
hubris|傲慢
humanism|人文主义
hybridity|混杂性
hyperbaton|倒装法
hyperbole|夸张法
hypertext|超文本
hypotaxis|主从结构
iamb|抑扬格
iconography|图像学
idealism|唯心主义
identification|认同
identity|身份
ideology|意识形态
idyll|田园诗
illusion|幻象
imagery|意象
imagism|意象派
imitation|模仿
imperialism|帝国主义
implication|暗示
implied-author|隐含作者
implied-reader|隐含读者
impressionism|印象派
incantation|咒语
incipit|卷首语
indeterminacy|不确定性
indexicality|指示性
in-medias-res|中间切入
intentional-fallacy|意图谬误
interior-monologue|内心独白
interpellated|被质询的
interpellation|质询
intersectionality|交织性
intertextuality|互文性
intonation|语调
intrigue|情节
inversion|倒装
irony|反讽
isotopy|同位素性
jacobean|詹姆斯一世时期的
jouissance|极乐
juxtaposition|并置
kenning|隐喻复合词
kitsch|媚俗艺术
kunstlerroman|艺术家小说
lacan|拉康(指代其理论)
lament|挽歌
lampoon|讽刺文
legend|传说
leitmotif|主导动机
lexicon|词汇表
liminality|阈限性
linguistics|语言学
lipogram|避讳诗
literal|字面的
literariness|文学性
litotes|曲言法
local-color|地方色彩
logocentrism|逻各斯中心主义
lyric|抒情诗
macabre|骇人的
magic-realism|魔幻现实主义
malapropism|词语误用
manifesto|宣言
marginalia|旁注
marxism|马克思主义
masque|假面剧
materialism|唯物主义
melodrama|情节剧
memoir|回忆录
metafiction|元小说
metalepsis|跨层叙述
metaphor|隐喻
metaphysical|玄学派的
meter|格律
metonymy|转喻
metrics|韵律学
mimesis|模仿
minimalism|极简主义
minstrelsy|游唱诗人的艺术
mise-en-abyme|戏中戏
mise-en-scène|场面调度
modernism|现代主义
monologue|独白
monometer|单步格
montage|蒙太奇
motif|母题
multiculturalism|多元文化主义
myth|神话
mythology|神话学
narration|叙事
narratology|叙事学
naturalism|自然主义
neoclassicism|新古典主义
neologism|新词
new-criticism|新批评
nihilism|虚无主义
nomadism|游牧主义
non-fiction|非虚构
nostalgia|怀旧
novel|小说
novella|中篇小说
objective-correlative|客观对应物
ode|颂诗
omniscient|全知的
ontology|本体论
onomatopoeia|拟声词
orientalism|东方主义
othering|他者化
oxymoron|矛盾修辞法
paean|赞歌
palindrome|回文
palimpsest|重写本
panegyric|颂词
panopticon|全景敞视监狱
pantheism|泛神论
parable|寓言
paradigm|范式
paradox|悖论
paralipsis|故作省略
parallelism|平行结构
paratext|副文本
parody|戏仿
pastiche|拼贴画
pastoral|田园诗
pathetic-fallacy|情感谬误
patriarchy|父权制
pedantry|卖弄学问
pentameter|五步格
peripeteia|突转
persona|面具、叙述者
personification|拟人
phenomenology|现象学
philology|文献学
picaresque|流浪汉小说
plot|情节
poetics|诗学
point-of-view|视角
polyphony|复调
polysemy|多义性
polysyndeton|连词叠用
post-colonialism|后殖民主义
post-humanism|后人类主义
postmodernism|后现代主义
post-structuralism|后结构主义
pragmatism|实用主义
pre-raphaelite|拉斐尔前派
prolepsis|闪前
prologue|序言
prose|散文
prosody|韵律学
protagonist|主人公
psychoanalysis|精神分析
pun|双关语
pyrrhic|抑抑格
quatrain|四行诗
queer-theory|酷儿理论
reader-response|读者反应批评
realism|现实主义
reception-theory|接受理论
refrain|叠句
regionalism|地方主义
renaissance|文艺复兴
repetition|重复
representation|表征
resolution|解决
rhetoric|修辞学
rhyme|押韵
rhythm|节奏
romance|传奇
romanticism|浪漫主义
satire|讽刺
scansion|韵律分析
semantics|语义学
semiotics|符号学
sensibility|感受力`,
  5: `
bad-faith|自欺
base-and-superstructure|经济基础与上层建筑
beatific-vision|荣福直观
behaviorism|行为主义
being-in-itself|自在之在
being-in-the-world|在世界中存在
being-toward-death|向死而生
bioethics|生命伦理学
brahman|梵
calvinism|加尔文主义
capitalism|资本主义
cartesianism|笛卡尔主义
categorical-imperative|绝对命令
causation|因果关系
chiliasm|千禧年主义
christology|基督论
clerisy|知识阶层
cognitivism|认知主义
coherence-theory|融贯论
collectivism|集体主义
common-sense|常识
communitarianism|社群主义
compatibilism|相容论
conceptualism|概念论
concupiscence|贪欲
consequentialism|后果主义
conservatism|保守主义
consubstantiation|同体论
contextualism|语境主义
contractarianism|契约论
conventionalism|约定论
correspondence-theory|符合论
cosmogony|宇宙生成论
cosmological-argument|宇宙论论证
cosmopolitanism|世界主义
creationism|神创论
critical-theory|批判理论
cultural-relativism|文化相对主义
cynic|犬儒主义者
dao|道
dasein|此在
death-of-god|上帝之死
death-of-the-author|作者之死
deism|自然神论
demiurge|造物主
democracy|民主
demythologization|非神话化
deontology|义务论
descriptive-ethics|描述伦理学
design-argument|设计论证
dharma|达摩
dialectical-materialism|辩证唯物主义
diaspora|大流散
dionysian|酒神的
dispensationalism|时代论
divine-command|神圣命令
docetism|幻影说
dogma|教条
dogmatism|教条主义
double-consciousness|双重意识
double-effect|双重效应
ecocentrism|生态中心主义
ecofeminism|生态女性主义
ecumenism|普世主义
egoism|利己主义
eidetic-reduction|本质还原
elan-vital|生命冲动
eleatic|埃利亚学派的
emanatism|流溢说
emotivism|情感主义
empiricism|经验主义
emptiness|空性
end-of-history|历史的终结
entelechy|隐德来希
enthymeme|省略三段论
epicureanism|伊壁鸠鲁主义
epiphenomenalism|副现象论
erastianism|国家至上论
eros|爱欲
essenes|艾赛尼派
eternal-return|永恒轮回
eternity|永恒
ethics|伦理学
eucharist|圣餐
eudaimonia|幸福
eugenics|优生学
eurocentrism|欧洲中心主义
eutychianism|一性论
evangelicalism|福音主义
evidentialism|证据主义
evil|恶
ex-cathedra|权威地
ex-nihilo|无中生有
existentialism|存在主义
experimentalism|实验主义
expiation|赎罪
expressionism|表现主义
externalism|外在主义
extropianism|外向主义
fallibilism|可错论
false-consciousness|虚假意识
falsification|证伪
fatalism|宿命论
feminism|女性主义
fideism|信仰主义
final-cause|目的因
first-cause|第一因
first-principles|第一性原理
flaneur|漫游者
foundationalism|基础主义
frankfurt-school|法兰克福学派
free-will|自由意志
functionalism|功能主义
fundamentalism|原教旨主义
gai-savoir|快乐的科学
game-theory|博弈论
general-will|公意
german-idealism|德国唯心主义
gestalt|格式塔
gnosticism|诺斯斯主义
god|上帝
golden-mean|中庸
golden-rule|黄金法则
good|善
grace|恩典
great-chain-of-being|存在之链
greatest-happiness-principle|最大幸福原则
halakha|哈拉卡
happiness|幸福
harm-principle|伤害原则
hedonism|享乐主义
hegelianism|黑格尔主义
hellenism|希腊化
henotheism|单一神论
hermeticism|赫尔墨斯主义
heteronomy|他律
heuristic|启发式
higher-criticism|高级批判
hinduism|印度教
historical-materialism|历史唯物主义
historicism|历史主义
holy-spirit|圣灵
hominization|人类化
humanism|人文主义
hylomorphism|质形论
hylozoism|物活论
hypothetico-deductive|假说演绎的
idealism|唯心主义
idolatry|偶像崇拜
ignorance|无明
illumination|光照
illusion|幻象
imagination|想象力
immanent-critique|内在批判
immaterialism|非物质主义
immortality|不朽
immutability|不变性
imperative|绝对命令
imperialism|帝国主义
implicit|隐含的
incarnation|道成肉身
incommensurability|不可通约性
individualism|个人主义
induction|归纳法
ineffable|不可言说的
infallibility|无误性
inference|推论
infinity|无限
in-itself|自在
innatism|天赋观念论
instrumentalism|工具主义
intellectualism|理智主义
interactionism|交互作用论
internalism|内在主义
intuitionism|直觉主义
irrationalism|非理性主义
islam|伊斯兰教
jainism|耆那教
jansenism|詹森主义
judaism|犹太教
just-war|正义战争
justice|正义
justification|确证
kabbalah|卡巴拉
kantianism|康德主义
karma|业力
kierkegaardian|克尔凯郭尔的
knowledge|知识
laissez-faire|自由放任
language-game|语言游戏
law|律法
legalism|律法主义
leviathan|利维坦
liberation-theology|解放神学
libertarianism|自由意志主义
liberty|自由
life-world|生活世界
logical-atomism|逻辑原子主义
logical-positivism|逻辑实证主义
lollardy|罗拉德派
love|爱
macchiavellianism|马基雅维利主义
madhyamaka|中观
magic|巫术
manichaeism|摩尼教
marxism|马克思主义
master-slave|主奴辩证法
maya|幻力
meaning|意义
mechanism|机械论
meliorism|社会改良论
mentalism|心灵主义
mercantilism|重商主义
mereology|部分整体论
messianism|弥赛亚主义
metamathematics|元数学
metaphilosophy|元哲学
metempsychosis|灵魂转世
methodological-individualism|方法论个人主义
microcosm|微观世界
mind-body|心身问题
miracle|奇迹
modal-logic|模态逻辑
modal-realism|模态实在论
moksha|解脱
monadology|单子论
monasticism|修道主义
monotheism|一神论
moral-hazard|道德风险
moral-realism|道德实在论
moral-relativism|道德相对主义
moral-sense|道德感
multiculturalism|多元文化主义
mutazilite|穆尔太齐赖派
mysticism|神秘主义
myth|神话
naive-realism|朴素实在论
narrative-theology|叙事神学
nationalism|民族主义
natural-law|自然法
natural-theology|自然神学
naturalism|自然主义
nature|自然
nazism|纳粹主义
necessitarianism|必然论
necessity|必然性
neo-confucianism|新儒家
neo-kantianism|新康德主义
neo-platonism|新柏拉图主义
neo-pragmatism|新实用主义
neo-scholasticism|新经院哲学
neo-thomism|新托马斯主义
new-age|新时代运动
nihilism|虚无主义
nirvana|涅槃
non-cognitivism|非认知主义
non-violence|非暴力
noumenon|本体
nous|理性
objectivism|客观主义
occasionalism|偶因论
oligarchy|寡头政治
omnipotence|全能
omnipresence|无所不在
omniscience|全知
ontological-argument|本体论论证
open-theism|开放神论
operationalism|操作主义
optimism|乐观主义
ordinary-language|日常语言哲学
organism|有机体
original-sin|原罪
orthodoxy|正统
orthopraxy|正行
paganism|异教
panentheism|万有在神论
pantheism|泛神论
paralogism|谬误推理
particularism|特殊主义
patriarchy|父权制
pelagianism|伯拉纠主义
perdurantism|接续论
perfectionism|完善论
peripatetic|逍遥学派的
personhood|位格、人格
pessimism|悲观主义
phenomenalism|现象主义
phenomenology|现象学
philosophy-of-language|语言哲学
philosophy-of-mind|心灵哲学
physicalism|物理主义
pietism|敬虔主义
platonism|柏拉图主义
pluralism|多元论
pneumatology|圣灵论
polytheism|多神论
positivism|实证主义
post-structuralism|后结构主义
postmodernism|后现代主义
pragmatism|实用主义
praxis|实践
predestination|预定论
premillennialism|前千禧年论
presbyterianism|长老宗
presentism|现在论
presuppositionalism|预设主义
probabilism|盖然论
process-theology|过程神学
protestantism|新教
providence|神意
psychoanalysis|精神分析
psychologism|心理主义
puritanism|清教主义
pythagoreanism|毕达哥拉斯主义
quakerism|贵格会
quietism|寂静主义
rationalism|唯理论
real-presence|真实临在
realism|实在论
reductionism|还原论
reformed-epistemology|改革宗认识论
reification|物化
relativism|相对主义
reliabilism|可靠论
renaissance|文艺复兴
representation|表征
reprobation|遗弃
resurrection|复活
revelation|启示
rule-utilitarianism|规则功利主义
sacrament|圣礼
salvation|救恩
sanctification|成圣
samsara|轮回
scholasticism|经院哲学
scientism|科学主义
scripture|经文
secularism|世俗主义
semantics|语义学
semiotics|符号学
sensationalism|感觉主义
shamanism|萨满教
shiism|什叶派
shinto|神道教
sikhism|锡克教
sin|罪
skepticism|怀疑论
social-contract|社会契约论
socialism|社会主义
solipsism|唯我论
sophism|诡辩
soteriology|救赎论
soul|灵魂
sovereignty|主权
spinozism|斯宾诺莎主义
spiritualism|唯灵论
stoicism|斯多葛主义
structuralism|结构主义
subjectivism|主观主义
sublime|崇高
substance|实体
sufism|苏菲派
sunnism|逊尼派
supererogation|分外善功
supervenience|随附性
syllogism|三段论
symbolism|象征主义
syncretism|混合主义
syndicalism|工团主义
synthetic-a-priori|先天综合
tabula-rasa|白板
taoism|道教
teleological-argument|目的论论证
`};

function parseEntries(source) {
  const parsedList = [];
  const lines = source.trim().split("\n");
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    if (line) {
      const parts = line.split("|");
      const termContent = parts[0];
      const meaningParts = [];
      for (let j = 1; j < parts.length; j++) {
        meaningParts.push(parts[j]);
      }
      parsedList.push({ termContent: termContent, meaning: meaningParts.join("|") });
    }
  }
  return parsedList;
}

async function main() {
  await database.initializeDatabase();
  const existingTerms = await database.all("SELECT termContent FROM aussieTerms");
  
  const seen = new Set();
  for (let i = 0; i < existingTerms.length; i++) {
    seen.add(existingTerms[i].termContent.trim().toLocaleLowerCase("en-AU"));
  }
  
  const additions = [];

  const keys = Object.keys(wordBanks);
  for (let k = 0; k < keys.length; k++) {
    const levelText = keys[k];
    const source = wordBanks[levelText];
    const level = Number(levelText);
    
    const entries = parseEntries(source);
    let addedForLevel = 0;
    
    for (let i = 0; i < entries.length; i++) {
      const entry = entries[i];
      if (!entry.termContent || !entry.meaning) {
        throw new Error(`Level ${level} contains an invalid entry: ${entry.termContent || "(missing term)"}`);
      }
      
      const normalized = entry.termContent.toLocaleLowerCase("en-AU");
      // 核心去重逻辑：如果原来的数据库中已经存在该单词，就直接跳过
      if (seen.has(normalized)) {
        continue;
      }
      
      seen.add(normalized);
      additions.push({ termContent: entry.termContent, meaning: entry.meaning, level: level });
      addedForLevel += 1;
      
      // 成功收集够 200 个不重复的单词后，停止当前等级的遍历
      if (addedForLevel === 200) {
        break;
      }
    }

    if (addedForLevel !== 200) {
      throw new Error(`Level ${level} has only ${addedForLevel} usable non-duplicate words.`);
    }
  }

  await database.run("BEGIN IMMEDIATE TRANSACTION");
  try {
    for (let i = 0; i < additions.length; i++) {
      const term = additions[i];
      await database.run(
        `INSERT INTO aussieTerms (termContent, meaning, example, termType, level)
         VALUES (?, ?, '', 'word', ?)`,
        [term.termContent, term.meaning, term.level]
      );
    }
    await database.run("COMMIT");
  } catch (error) {
    await database.run("ROLLBACK");
    throw error;
  }

  console.log(`Added ${additions.length} words: 200 words for each level.`);
}

main()
  .catch((error) => {
    console.error(error.message);
    process.exitCode = 1;
  })
  .finally(() => database.close());